language: node_js
sudo: false
node_js:
- '0.10'
- '0.12'
- '4'
- '5'
deploy:
  provider: npm
  email: npmjs@skipatrolguy.com
  api_key:
    secure: q73+UDTvIiR+rekIRAeCblBZqF3nQdR+0wnI3Llb6jvZYS6Sw3/S1aJprrzKU+falHSHR3Xj1ooLsV+BFuvPo9b39tAOD295R7xsCQZt9Py3kaUV745GleABJqyQyCwjvY0Bjr8LhEfxVwjD7taEZJT3v1gRrpxDCTM2CaA7UCNJ6sohjBZTfY3S0v2IvpOCmoHejdyMRSKA5dyI8o7xHPlcOodqTQmy1Fjt+egMKTH+j+p4ZBOi/f2rqJoKv1NSi+TLmJAfVmJlJjwXr5UTwjNkhS+JietCUDTPkvvHxk1z1zveCgCWwz0SrfTshOzRUR+90/Xhn/oqhHGUc8/6vfHRqYw9s6snZsznOXIW0ZnLFSDN3FTEuOPft/0CCQ9Po7b249DMsMa2IwyiGYUqSl/kQFN2aXCWbEk+ql8NTfB6H0PXaoKnieRUvpzHRmBlKx81Q1fTrPpWQXc0FmXz/gHCP9rCi9lEGkWoP9iRVNPhBZrcctCJLFsgC2olU2Q0n/GCuVEcObmIGdnnObAMvRvmk1X9qBDJ0BFoITqX6JMYZXavewTH0dpLlszdPlWfnTdgP5W6EM6Jt7xyseAn6gLCt/IJ8WnXubb3XPBbVFIUX1oYba1eDmu3TPRuJwYQG0a8NhEQxlfPwNfQSqTygIaNgWMcGlWCTSJ07BCSIq0=
  on:
    tags: true
    repo: Furchin/merge-cidrs
